### ISSUE TITLE
Exception: module 'random' has no attribute 'choices'

### ISSUE THREAD

**Issue by eskimo** [josephbisch/pyircfuzz#1]
Can't seem to get this running right no matter what I try. Keep getting this same error. Any ideas?

**Comment by DanielOaks** [comment]
Hmm, you may need to update to Python 3.6 if you're not on that version already. Looks like Py 3.5 and 2.7 both lack it. Otherwise, could modify [this line](https://github.com/josephbisch/pyircfuzz/blob/master/ircfuzz.py#L19) appropriately

**Comment by eskimo** [comment]
Oh hey dan :P

But yeah I'm on python 3.5. I'll update. Btw I'm klined from freenode still that's why I haven't been around lol.

**Comment by DanielOaks** [comment]
Ahh fairfair, heh gotta love it :P

**Comment by eskimo** [comment]
Upgrading worked. And now I'm stuck fixing crashes for a while. The readme should probably mention the minimum of 3.6 o.O

Thanks homie :)
